Use maximum chromatogram intensity as Area for MS2 transitions when acquisition method is DDA
ProteoWizard/pwiz pull request #2013
Opened 2022-02-24 03:55 UTC by nickshulman

In order to make it so that the Library Dot Product is a useful number, we have decided that when the acquisition method is DDA, the Area of the MS2 transitions will be based on the intensity at the best point on the chromatogram between the peak boundaries. The best point is determined by finding the point at which the sum of the intensities across the MS2 transitions is highest.

2022-02-28 18:40 UTC, brendanx67 requested changes
Looks like a good start. I don't think you quite have all of the peak statistics right yet. It looks like this just corrects Area. Also, I think you are going to need more complete testing of this change.

2022-02-28 18:40 UTC, brendanx67 commented on pwiz_tools/Skyline/Model/Results/PeakIntegrator.cs
> +        /// be the intensity at the time point with the highest total MS1 intensity
The code looks like you are using highest total MS2 intensity. So, I think this comment is incorrect.

2022-02-28 18:40 UTC, brendanx67 commented on pwiz_tools/Skyline/Model/Results/ChromHeaderInfo.cs
> +        private float _area;
I think more than just the area needs to change. Background needs to become zero. Height and area should become equal. FWHM also needs to become zero. Mass error needs to become the mass error at the single point, points across peak should be 1. And the RT needs to become the RT of the single spectrum for all transitions, not the time at which each has its maximum intensity within start-end time.

2022-03-27 17:58 UTC, brendanx67 commented
I think we can abandon this one in favor of using area without background subtraction in PR#2034

2022-03-28 23:13 UTC, nickshulman commented
Closing this pull request since PR #2034 ended up doing much better.

2022-03-28 23:13 UTC, closed without merging