Support for show/hide neutral losses spectrum annotation
ProteoWizard/pwiz pull request #2066
Opened 2022-04-06 03:24 UTC by rita-gwen

Replaced the context menu items for ion type and charge selection with specialized menu-hosted controls.

2022-04-21 23:37 UTC, rita-gwen commented on pwiz_tools/Skyline/SkylineGraphs.cs
> +            CollectionUtil.ForEach(FormUtil.OpenForms.OfType<FoldChangeForm>(), f => f.Close());
This is a strange change, I don't remember doing it. Might has come from a master merge.

2022-04-21 23:46 UTC, rita-gwen commented
This PR is ready for the code review.

2022-04-25 21:24 UTC, rita-gwen commented
This is how it looks with enough losses defined:
<img width="400" height="400" src="https://user-images.githubusercontent.com/13304700/165177169-1464d4f5-ce56-4638-bfbc-99e4cf489712.png"/>

2022-05-12 18:47 UTC, brendanx67 requested changes
Found my review. Mostly pretty minor stuff, but needs a bit more testing.

2022-06-02 19:30 UTC, rita-gwen commented
I was thinking how to address that extra border problem when a button on the control has focus. Do you think this style will work? It doesn't have borders at all.
<img src="https://user-images.githubusercontent.com/13304700/171722141-8147ae63-25c3-4a44-a7be-7263c60592cd.png" width="500" height="200"/>

2022-06-28 02:50 UTC, merged