Skyline/work/20220624 redundant spectra dropdown view spectral libraries
ProteoWizard/pwiz pull request #2138
Opened 2022-06-28 21:01 UTC by aaronigra

Support for a dropdown in the view spectral libraries menu to view redundant spectra matches in the given library.

2022-06-29 19:41 UTC, nickshulman commented on pwiz_tools/Skyline/SettingsUI/ViewLibraryDlg.cs
> +            public SpectrumInfoLibrary library;
This field should be called "spectrumInfo", or maybe "spectrumInfoLibrary". 

A "SpectrumInfoLibrary" is a type of "SpectrumInfo", not a type of "Library".

2022-07-01 23:18 UTC, brendanx67 requested changes
Looking good. My requested changes should be pretty quick.

2022-07-01 23:18 UTC, brendanx67 commented on pwiz_tools/Skyline/SettingsUI/ViewLibraryDlg.cs
> +                    SpectrumPeaksInfo isLoadableSpectrum;
Usually, a name like "is..." would be reserved for a boolean value. Maybe something like loadedSpectrum?

2022-07-01 23:18 UTC, brendanx67 commented on pwiz_tools/Skyline/SettingsUI/ViewLibraryDlg.cs
> +                        // var bestSpectrum = _selectedLibrary.GetSpectra(_peptides[index].Key,
Not sure we need the old code in a comment here.

2022-07-01 23:18 UTC, brendanx67 commented on pwiz_tools/Skyline/SettingsUI/ViewLibraryDlg.cs
> +                        comboRedundantSpectra.SelectedIndexChanged -= redundantSpectrum_changed;
Worth adding a comment here about what you are doing, i.e. avoid updating the UI.

2022-07-01 23:18 UTC, brendanx67 commented on pwiz_tools/Skyline/TestTutorial/TargetedMSMSTutorialTest.cs
> -
Doesn't seem like a relevant change.

2022-07-01 23:18 UTC, brendanx67 commented on pwiz_tools/Skyline/TestTutorial/TargetedMSMSTutorialTest.cs
> +
Doesn't seem like a relevant change.

2022-07-01 23:18 UTC, brendanx67 commented on pwiz_tools/Skyline/TestTutorial/TargetedMSMSTutorialTest.cs
> +        //Tests the redundant spectrum dropdown menu in the ViewSpectralLibraries dialogue
Use a C# header comment more like this: 

/// &lt;summary>
/// Tests the redundant spectrum dropdown menu in the &lt;see ref="ViewLibraryDlg" /> form
/// &lt;/summary>

2022-07-01 23:18 UTC, brendanx67 commented on pwiz_tools/Skyline/TestTutorial/TargetedMSMSTutorialTest.cs
> +            var dlg = ShowDialog<ViewLibraryDlg>(SkylineWindow.ViewMenu.ViewSpectralLibraries);
Add some comments below about what you are testing.

2022-07-01 23:18 UTC, brendanx67 commented on .gitignore
> +/pwiz_aux/msrc/utility/vendor_api/Bruker/BAF2SQL-README.txt
You just mentioned this, but you should not need to alter .gitignore for the project.

2022-07-05 22:19 UTC, bspratt commented on pwiz_tools/Skyline/SettingsUI/ViewLibraryDlg.cs
> +                        //Get all redundant spectrum for the selected peptide, add them to comboRedundantSpectra
Totally nitpicking here, but our commenting style has a leading space (and, good, capital letter)

2022-07-05 22:23 UTC, bspratt commented on pwiz_tools/Skyline/SettingsUI/ViewLibraryDlg.cs
> +                        //Get all redundant spectrum for the selected peptide, add them to comboRedundantSpectra
(But, a wise coder once told me that "The only proper code formatting style is the one that's already in use." The idea is not to trip up the eye of whoever is digging through your code looking for who-knows-what.)

2022-07-05 22:26 UTC, bspratt submitted a review, later dismissed
This looks good though I would encourage you to go through and make your comments look like all the others already there. It's not busy work,. I promise you.

2022-07-06 16:55 UTC, bspratt commented
Also make sure you deal with ReSharper code inspection warnings, if you haven't already. You can run those locally, and they also happen on TeamCity https://teamcity.labkey.org/viewLog.html?buildId=1881735&tab=Inspection&buildTypeId=ProteoWizard_WindowsX8664msvcProfessionalSkylineResharperChecks

2022-07-12 01:37 UTC, brendanx67 commented
One last thought: You should be using ComboHelper.AutoSizeDropDown() when you change the contents of the dropdown list. That way a user doesn't have to resize the entire form just to see the full contents of the dropdown list when the file names are very long.

2022-07-14 00:52 UTC, brendanx67 commented
Okay. Looks very close to me now after a bit of clean-up. Let's go over the core function to update the combo box, and then we should be able to merge it tomorrow.

2022-07-14 22:42 UTC, brendanx67 approved these changes

2022-07-15 17:59 UTC, merged