Update Library Viewer context menu
ProteoWizard/pwiz pull request #2308
Opened 2022-09-27 20:57 UTC by rita-gwen

2022-10-19 18:13 UTC, brendanx67 requested changes
There are still consistency issues with these menus across all of the places they are shown:
1. The View menu on the main menu
2. Right-click in the Library Match view
3. Right-click in the Spectral Library Explorer
4. Right-click in the Full-Scan graph (when spectrum annotation is on)

The Spectral Library Explorer has an extra splitter above "Charges" that should be removed. The View menu doesn't use the new menu pushbutton UI.

Also, the right-click menus end with a splitter instead of having a splitter above Undo Zoom.

2022-10-31 23:07 UTC, rita-gwen commented
All menus that set ion types and charges are synchronized. The screenshots are here:
![image](https://user-images.githubusercontent.com/13304700/199126333-b6276951-042e-4a97-b66c-518cfe376b17.png)

2022-11-02 19:19 UTC, brendanx67 approved these changes

2022-11-02 19:26 UTC, brendanx67 requested changes
The RESX file changes in ViewLibraryDlg make this change incompatible with a cherry-pick back to 22.2. You will need to implement a much smaller change there to fix the menus that got broken between 21.2 and 22.2, but not go this far with fully normalizing all menu cases.

2022-11-02 19:26 UTC, brendanx67 commented on pwiz_tools/Skyline/SettingsUI/ViewLibraryDlg.resx
> +    <value>31, 28</value>
All these size changes make me a little concerned.

2022-12-02 00:18 UTC, rita-gwen commented
I added missing Special Ions item to the main window View menu and fixed broken logic of the Score menu item in the Library Match viewer.

2022-12-05 19:28 UTC, merged