Update old BuildMethod projects to .NET Framework 4.7.2
ProteoWizard/pwiz pull request #2464
Opened 2023-01-19 19:16 UTC by kaipot

Visual Studio complains about projects targeting .NET Framework 4.0 not being supported. Also, 4.0 targeting pack is really hard to find anywhere for download at this point (the only way I could get it was by installing it through the Visual Studio 2017 installer).

2023-01-22 17:27 UTC, brendanx67 requested changes
Don't we at the same time want to update the EXE files under Method? This seems like it will update the target in those EXE files the next time we build them but doesn't actually do that for our next release.

2023-01-23 17:37 UTC, kaipot commented
> Don't we at the same time want to update the EXE files under Method? This seems like it will update the target in those EXE files the next time we build them but doesn't actually do that for our next release.

Updating the actual binaries at the same time is a good idea. I rebuilt them with the new configs.

2023-01-23 19:34 UTC, brendanx67 approved these changes

2023-01-24 03:11 UTC, nickshulman approved these changes

2023-01-24 19:26 UTC, merged