Add protein expression plot
ProteoWizard/pwiz pull request #2807
Opened 2023-12-07 20:31 UTC by henrytsanford

In progress, still lots of optimization left

2023-12-27 22:37 UTC, brendanx67 requested changes
Looking good. Still some work to be done on this.

2023-12-27 22:37 UTC, brendanx67 commented on pwiz_tools/Skyline/SkylineGraphs.cs
> +            foreach (var summary in _listGraphPeakArea.Where(summary => summary.Type == GraphTypeSummary.abundance))
Can there possibly ever be more than one of these? Maybe just find it using FirstOrDefault()

2023-12-27 22:37 UTC, brendanx67 commented on pwiz_tools/Skyline/SkylineGraphs.cs
> +            SynchronizeSummaryZooming();
I can't see how this would apply to this graph. I don't think you could synchronize this with any other graph.

2023-12-27 22:37 UTC, brendanx67 commented on pwiz_tools/Skyline/SkylineGraphs.cs
> +        public void setAreaProteinTargets(bool areaProteinTargets)
Use title casing, not camel casing. Camel case is for event handlers only.

2023-12-27 22:37 UTC, brendanx67 commented on pwiz_tools/Skyline/SkylineGraphs.cs
> +        public void setExcludePeptideListsFromAbundanceGraph(bool excludePeptideLists)
Use title case

2023-12-27 22:37 UTC, brendanx67 commented on pwiz_tools/Skyline/SkylineGraphs.cs
> +                case GraphTypeSummary.abundance:
This seems a bit strange that the abundance graph should share a properties form with the comparison forms.

2023-12-27 22:37 UTC, brendanx67 commented on pwiz_tools/Skyline/TestFunctional/PeakAreaRelativeAbundanceGraphTest.cs
> +                //CONSIDER add quantitative checks for relative abundance results
Feels like you should also be adding testing of the formatting forms in this context.

2023-12-27 22:37 UTC, brendanx67 commented on pwiz_tools/Skyline/TestFunctional/VolcanoPlotFormattingTest.cs
> +                Assert.AreEqual(createExprDlg.Expression, "^Cas9$|^Hsp70$");
Ideally, you would have some edge/error case testing, like when you add things that don't match, or you add empty lines, etc. I can imagine wanting the matches to be case-insensitive also. Looks like you have only case-sensitive matching?

2024-01-04 22:05 UTC, rita-gwen commented
It looks like there are still some fixes needed before this can be merged. Properties context menu does nothing. Selection context menu item seems to do nothing. If some formatting criteria are specified it probably should show a legend.

2024-01-04 23:29 UTC, brendanx67 commented
On the last one, we are just trying to be comparable to the volcano plot.
Let's get this to the level of that plot and make a first checkpoint merge.
Then we can return to ways that both plots can be improved. I would
probably go for the label placement work over the legend in a list of
priorities for both plots.

On Thu, Jan 4, 2024 at 2:05 PM Rita Chupalov ***@***.***>
wrote:

> It looks like there are still some fixes needed before this can be merged.
> Properties context menu does nothing. Selection context menu item seems to
> do nothing. If some formatting criteria are specified it probably should
> show a legend.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ProteoWizard/pwiz/pull/2807#issuecomment-1877823207>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACYBWUHQCYTX3HGZSD2SFNLYM4RTPAVCNFSM6AAAAABALU3WNKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNZXHAZDGMRQG4>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-01-16 19:01 UTC, merged