Avoid some potential test race conditions by being explicit about which tests need DismissAutoManageDialog()…
ProteoWizard/pwiz pull request #2922
Opened 2024-04-09 21:33 UTC by bspratt

… and which do not.

2024-04-10 19:02 UTC, brendanx67 requested changes
I think the use of conditions versus straight assertions could be improved in DismissAutoManageDialog()

2024-04-10 19:02 UTC, brendanx67 commented on pwiz_tools/Skyline/TestUtil/TestFunctional.cs
> +            else if (IsFormattedMessage(Resources.SkylineWindow_ImportMassList_Do_you_want_to_use_the_document_settings_to_automanage_these_new_transitions, autoManageDlg.Message))
This feels like it should be replaced with a simple assert, getting rid of the if clause entirely and the need to call AssertEx.Fail() yourself.

2024-04-11 21:27 UTC, brendanx67 approved these changes

2024-04-11 21:30 UTC, brendanx67 commented
I simplified the DismissAutoManageDialog() function a bit more and removed IsFormattedMessage() in favor of using AssertEx.AreComparableStrings(). I also ended up improving diagnostics to help understand failures I saw running parallel tests. Sorry for adding unrelated changes to your PR.

2024-04-11 21:42 UTC, bspratt commented
I like my implementation better as it tells you exactly what the test was waiting for (the AutoManage dialog) rather than just "I was expecting a generic message dialog", but not enough to make a fuss about it.

2024-04-11 22:02 UTC, brendanx67 commented
Yeah. You can learn that from the call stack pretty easily. Not worth adding code complexity to put that in the message.

2024-04-11 22:07 UTC, brendanx67 commented
I set the timeout to 1 millisecond to see what a failure report looks like. Funny that by the time it starts reporting the failure the MultiButtonMsgDlg is present, but you can see that DismissAutoManageDialog is in the callstack.

Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException: Assert.Fail failed. Timeout 0 seconds exceeded in WaitForOpenForm(MultiButtonMsgDlg). Open forms: SequenceTreeForm (), SkylineWindow (Skyline), MultiButtonMsgDlg ()
   at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.HandleFailure(String assertionName, String message)
   at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.Fail(String message, Object[] parameters)
   at pwiz.SkylineTestUtil.AbstractFunctionalTest.WaitForOpenForm[TDlg](Int32 millis) in C:\proj\pwiz\pwiz_tools\Skyline\TestUtil\TestFunctional.cs:line 783
   at pwiz.SkylineTestUtil.AbstractFunctionalTest.DismissAutoManageDialog() in C:\proj\pwiz\pwiz_tools\Skyline\TestUtil\TestFunctional.cs:line 2198

2024-04-12 13:50 UTC, merged