Show warning when training mProphet model if explicit peak bounds from libraries are being used
ProteoWizard/pwiz pull request #2984
Opened 2024-05-25 17:07 UTC by nickshulman

Changed to show warning message when adding decoys or training mProphet model if document uses explicit peak bounds from spectral libraries.
Changed to show warning tooltip on Transition Settings Full Scan tab if retention time filtering is used with PRM acquisition method.

Also speed up "Library.FindSource" so that it remembers its answers because EncyclopeDiaLibrary was really slow sometimes. The logic for matching MsDataFileUri's to library source file names is now in class "LibraryFiles" instead of duplicated in EncyclopeDiaLibrary, BiblioSpecLiteLibrary and ChromatogramLibrary.

Warning message for "Refine > Add Decoys":
![image](https://github.com/ProteoWizard/pwiz/assets/303203/a94fa1ab-fa28-4082-97d3-e8071db09af0)

Warning message using "<Add...>" or "<Edit Current...>" at "Refine > Reintegrate":
![image](https://github.com/ProteoWizard/pwiz/assets/303203/f691b845-1a6f-426a-8c55-d1b34c5888be)

Warning tooltip if using retention time filtering with PRM:
![image](https://github.com/ProteoWizard/pwiz/assets/303203/7a0d18a9-0027-40ca-bedd-126618bf8ee1)
("SureQuant" or "Targeted" may be displayed instead of "PRM").

2024-05-28 23:04 UTC, brendanx67 commented
I don't love the use of "OK | Cancel" here. These are pretty broken things to do, and "OK" is the default. Also "OK" is not a valid response to "Are you sure... ?" I suppose it might be better to use "Yes" and "No", with no default or "No" as default.

Or use "Add Decoys" and "Cancel" ("Train Model" and "Cancel") with no default.

2024-05-28 23:17 UTC, brendanx67 requested changes
Surprising that this requires no test changes. Please add testing of the new UI.

2024-05-28 23:17 UTC, brendanx67 commented on pwiz_tools/Skyline/Menus/MenusResources.resx
> +1. Navigate to the "Libraries" tab at "Settings > Peptide Settings" and edit the library list.
Navigate to the "Settings > Peptide Settings - Libraries" tab, and click "Edit List".

2024-05-28 23:17 UTC, brendanx67 commented on pwiz_tools/Skyline/Menus/MenusResources.resx
> +2. Edit the library items and uncheck the "Use explicit peak bounds" checkbox.</value>
Select a library item, click "Edit", and uncheck the "Use explicit peak bounds" checkbox.

2024-05-28 23:17 UTC, brendanx67 commented on pwiz_tools/Skyline/SettingsUI/SettingsUIResources.resx
> +1. Navigate to the "Libraries" tab at "Settings > Peptide Settings" and edit the library list.
Make consistent with other instance of these instructions per review.

2024-05-28 23:17 UTC, brendanx67 commented on pwiz_tools/Skyline/SettingsUI/SettingsUIResources.resx
> +3. Navigate to 'Edit > Manage Results' and click the 'Re-score' button.
Use double quotes for consistency.

2024-05-29 03:55 UTC, nickshulman commented
> I don't love the use of "OK | Cancel" here. These are pretty broken things to do, and "OK" is the default. Also "OK" is not a valid response to "Are you sure... ?" I suppose it might be better to use "Yes" and "No", with no default or "No" as default.
> 
> Or use "Add Decoys" and "Cancel" ("Train Model" and "Cancel") with no default.

I updated the message text and the button text.

I actually can't figure out how to make it so the MultiButtonMsgDlg has no default (accept) button.

Since the form has only two buttons on it, one of those two buttons is going to have the focus, and is therefore going to respond to the Enter key.
However, I cannot even figure out how to make it so the Cancel button is the default button.
That is, even if I set "dlg.AcceptButton = dlg.CancelButton", the other button still ends up being the one that is selected when the dialog comes up ("dlg.AcceptButton = null" does not work either).

I even tried this with a simpler form ("PasteFilteredPeptidesDlg") and I could not get it to have either no default button or have it so the Cancel button is the default button.

2024-05-29 21:14 UTC, merged